In [1]:
import numpy as np


# NumPy Practical 2

In [4]:
a1=np.random.randn(5)

In [5]:
a1

array([-1.44902136, -0.69337894, -2.20397162, -0.87646285, -1.68763395])

In [7]:
a2=np.array([[-7,10,4,3,2],[1,4,5,0,6],[3,2,-1,0,4]])

In [8]:
a2

array([[-7, 10,  4,  3,  2],
       [ 1,  4,  5,  0,  6],
       [ 3,  2, -1,  0,  4]])

In [9]:
a2[::-1]

array([[ 3,  2, -1,  0,  4],
       [ 1,  4,  5,  0,  6],
       [-7, 10,  4,  3,  2]])

In [10]:
a2[0:1,0:]

array([[-7, 10,  4,  3,  2]])

In [11]:
a2[0:2,0:2]

array([[-7, 10],
       [ 1,  4]])

In [14]:
a=sort(a2,axis=1)

NameError: name 'sort' is not defined