## Practical 4 (Pandas series)
### Name = Shrutika Bhosle
### Roll No. = 403

In [2]:
import numpy as np
import  pandas as pd

## 1. Create the following Series and do the specified operations:

#### a) EngAlph, having 26 elements with the alphabets as values and default index values.

In [3]:
EngAlph= pd.Series(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'])

In [4]:
EngAlph.head() # print only starting 5 colomns

0    a
1    b
2    c
3    d
4    e
dtype: object

#### b) Vowels, having 5 elements with index labels ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’ and all the five values set to zero. Check if it is an empty series.

In [5]:
vow=pd.Series(0,index=['a','e','i','o','u'])

In [6]:
vow

a    0
e    0
i    0
o    0
u    0
dtype: int64

In [10]:
vow=pd.Series(1,index=['a','e','i','o','u'])
vow

a    1
e    1
i    1
o    1
u    1
dtype: int64

#### c) Friends, from a dictionary having roll numbers of five of your friends as data and their first name as keys.


In [7]:
fd={'sahil':413,'anjali':414,'shalu':5646,'Shrutika':403,'arpit':404}
fds=pd.Series(fd)
fds

sahil        413
anjali       414
shalu       5646
Shrutika     403
arpit        404
dtype: int64

In [13]:
name={'nayan':4,'sahil':64}
name

{'nayan': 4, 'sahil': 64}

#### d) MTseries, an empty Series. Check if it is an empty series.

In [8]:
MTseries = pd.Series()
MTseries

C:\Users\khuje\AppData\Local\Temp\ipykernel_11416\3850582936.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  MTseries = pd.Series()


Series([], dtype: float64)

#### e) MonthDays, from a numpy array having the number of days in the 12 months of a year. The labels should be the month numbers from 1 to 12.

In [9]:
MonthDays = pd.Series(np.array([31,28,31,30,31,30,31,31,30,31,30,31]),index=[1,2,3,4,5,6,7,8,9,10,11,12])
print(MonthDays)

1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9     30
10    31
11    30
12    31
dtype: int32


In [10]:
MonthDays2 = pd.Series(['jan','feb','march','april','may','jun','july','aug','sept','oct','nov','dec'],index=['1','2','3','4','5','6','7','8','9','10','11','12'])
print(MonthDays2)

1       jan
2       feb
3     march
4     april
5       may
6       jun
7      july
8       aug
9      sept
10      oct
11      nov
12      dec
dtype: object


## 2. Using the Series created in Question 1, write commands for the following:


#### a) Set all the values of Vowels to 10 and display the Series.

In [11]:
vow['a':'u']=10
vow

a    10
e    10
i    10
o    10
u    10
dtype: int64

#### b) Divide all values of Vowels by 2 and display the Series.

In [12]:
div=vow/2
div

a    5.0
e    5.0
i    5.0
o    5.0
u    5.0
dtype: float64

#### c) Create another series Vowels1 having 5 elements with index labels ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’ having values [2,5,6,3,8] respectively.

In [14]:
vowels1 = pd.Series([2,5,6,3,8],index=['a','e','i','o','u'])
vowels1

a    2
e    5
i    6
o    3
u    8
dtype: int64

#### d) Add Vowels and Vowels1 and assign the result to Vowels3

In [14]:
vowaddition=vow+vowels1 # addition
vowaddition

a    12
e    15
i    16
o    13
u    18
dtype: int64

#### e) Subtract, Multiply and Divide Vowels by Vowels1.

In [15]:
print("subtraction")
subt=vow-vowels1 #Subtraction
print(subt)
mult=vow*vowels1 #multiplication
print("multiplication")
print(mult)


subtraction
a    8
e    5
i    4
o    7
u    2
dtype: int64
multiplication
a    20
e    50
i    60
o    30
u    80
dtype: int64


#### f) Alter the labels of Vowels1 to [‘A’, ‘E’, ‘I’, ‘O’, ‘U’]

In [16]:
vowels1.index=['A','E','I','O','U']
vowels1

A    2
E    5
I    6
O    3
U    8
dtype: int64

## 3. Using the Series created in Question 1, write commands for the following:

#### a) Find the dimensions, size and values of the Series EngAlph, Vowels, Friends, MTseries, MonthDays.

In [17]:
#for EngAlph
print(EngAlph.ndim)# for dimensions
print(EngAlph.size) #for size
print(EngAlph.values)#for values

1
26
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [18]:
#for Vowels
print(vow.ndim)# for dimensions
print(vow.size) #for size
print(vow.values)#for values

1
5
[10 10 10 10 10]


In [19]:
#for Friends
print(fds.ndim)# for dimensions
print(fds.size) #for size
print(fds.values)#for values

1
5
[ 413  414 5646  403  404]


In [20]:
#for MTseries
print(MTseries.ndim)# for dimensions
print(MTseries.size) #for size
print(MTseries.values)#for values

1
0
[]


In [21]:
#for MonthDays
print(MonthDays.ndim)# for dimensions
print(MonthDays.size) #for size
print(MonthDays.values)#for values

1
12
[31 28 31 30 31 30 31 31 30 31 30 31]


#### b) Rename the Series MTseries as SeriesEmpty

In [22]:
SeriesEmpty=MTseries.rename()
print(SeriesEmpty)

Series([], dtype: float64)


#### c) Name the index of the Series MonthDays as monthno and that of Series Friends as Fname.

In [23]:
MonthDays.index.name=("monthno")
MonthDays

monthno
1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9     30
10    31
11    30
12    31
dtype: int32

In [24]:
fds.index.name=("fname")
fds

fname
sahil        413
anjali       414
shalu       5646
Shrutika     403
arpit        404
dtype: int64

#### d) Display the 3rd and 2nd value of the Series Notes Friends, in that order.


In [25]:
fds['Shrutika'] #for 3rd 

403

In [26]:
fds['shalu'] #for 2nd

5646

#### e) Display the alphabets ‘e’ to ‘p’ from the Series EngAlph.

In [27]:
print(EngAlph[4:16])

4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
dtype: object


#### f) Display the first 10 values in the Series EngAlph.

In [28]:
print(EngAlph.head(10))

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
dtype: object


#### g) Display the last 10 values in the Series EngAlph.

In [29]:
print(EngAlph.tail(10))

16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


#### h) Display the MTseries.

In [30]:
print(MTseries)

Series([], dtype: float64)


## 4. Using the Series created in Question 5, write commands for the following:

#### a) Display the names of the months 3 through 7 from the Series MonthDays2.

In [31]:
print(MonthDays2['3':'7'])

3    march
4    april
5      may
6      jun
7     july
dtype: object


#### b) Display the Series MonthDays2 in reverse order.

In [32]:
print(MonthDays2[::-1])
print(MonthDays[::-1])

12      dec
11      nov
10      oct
9      sept
8       aug
7      july
6       jun
5       may
4     april
3     march
2       feb
1       jan
dtype: object
monthno
12    31
11    30
10    31
9     30
8     31
7     31
6     30
5     31
4     30
3     31
2     28
1     31
dtype: int32
