# NumPy Practical 2

#### Roll no.407  
#### Name : Nayan khuje

In [1]:
import numpy as np

## Q1

##### a) Create a one -dimensional array consist of any 10 negative numbers.

In [2]:
a=np.array([-1,-2,-3,-3,-6,-7,-17,-12,-15,-1])

##### b) Create a 2-dimensional array consists of any 12 numbers.

In [3]:
b=np.array([[1,2,1,4,5,5],[4,5,8,4,6,9]])
print(b)

[[1 2 1 4 5 5]
 [4 5 8 4 6 9]]


##### c) Create a 1-dimensional array consists of first 10 odd natural numbers.

In [4]:
c=np.array([1,3,5,7,9,11,13,15,17,19])
print(c)

[ 1  3  5  7  9 11 13 15 17 19]


In [12]:
c.reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [5]:
c=np.arange(1,20,2)
print(c)

[ 1  3  5  7  9 11 13 15 17 19]


In [9]:
c1=np.arange(5,51,5)
c1

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

##### d) Create a 2-dimensional array with 4 rows and 5 columns with all entry 0.

In [10]:
d=np.zeros([4,5])
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


##### e) Create a 2-dimensional array with 3 row and 4 columns with all entries 2.4.

In [18]:
e=np.full((3,4),2.4)
print(e)

[[2.4 2.4 2.4 2.4]
 [2.4 2.4 2.4 2.4]
 [2.4 2.4 2.4 2.4]]


##### f) Using arange() method create a 2-dimensional array with 2 rows and 5 columns with starting value 2 and values are increased by 3.

In [11]:
f=np.arange(2,30,3).reshape(2,5)
print(f)

[[ 2  5  8 11 14]
 [17 20 23 26 29]]


##### g) Using reshape(), create a 2-dimensional array with 2 rows and 5 columns using the array created in Q.1 a

In [43]:
g=a.reshape(2,5)
print(g)

[[ -1  -2  -3  -3  -6]
 [ -7 -17 -12 -15  -1]]


##### h) Create a 2-dimensional array with 4 rows and 5 columns with random values in it.


In [46]:
h=np.random.rand(4,5)
print(h)

[[0.45305903 0.01980625 0.33845973 0.06215952 0.67024461]
 [0.39822658 0.97086345 0.58622444 0.82871962 0.36224319]
 [0.27812149 0.84840827 0.56680048 0.22792051 0.65448341]
 [0.02468703 0.43703767 0.83429562 0.66989516 0.59431323]]


In [13]:
h1=np.random.rand(5,4)
h1

array([[0.42548181, 0.2003089 , 0.49571065, 0.21138405],
       [0.31115047, 0.19042346, 0.22884389, 0.56292334],
       [0.13088531, 0.9738698 , 0.40714048, 0.58026299],
       [0.42546634, 0.27428328, 0.21659153, 0.06032426],
       [0.23308522, 0.26111998, 0.93034834, 0.00250379]])

# Q 2

##### . a) Display the dimension, shape, size, data type, size of each element of the array, for all the array created above.

In [50]:
#for a
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)

1
(10,)
10
int32
4


In [51]:
#for b
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)

2
(2, 6)
12
int32
4


In [57]:
#for c
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)

1
(10,)
10
int32
4


In [58]:
#for d
print(d.ndim)
print(d.shape)
print(d.size)
print(d.dtype)
print(d.itemsize)

2
(4, 5)
20
float64
8


In [59]:
#for e
print(e.ndim)
print(e.shape)
print(e.size)
print(e.dtype)
print(e.itemsize)

2
(3, 4)
12
float64
8


In [127]:
#for f
print(f.ndim)
print(f.shape)
print(f.size)
print(f.dtype)
print(f.itemsize)

2
(2, 5)
10
int32
4


In [61]:
#for g
print(g.ndim)
print(g.shape)
print(g.size)
print(g.dtype)
print(g.itemsize)

2
(2, 5)
10
int32
4


In [62]:
#for h
print(h.ndim)
print(h.shape)
print(h.size)
print(h.dtype)
print(h.itemsize)

2
(4, 5)
20
float64
8


##### b) Display the first, second, last and second last element of the array created in the question 1.

In [65]:
#for a (1 dim)
print(a[0]) #first
print(a[1]) #second
print(a[-1]) #last
print(a[-2]) #second last

-1
-2
-1
-15


In [70]:
#for b (2 dim)
print(b[0,0]) #first
print(b[0,1]) #second last row wise
print(b[1,0]) #second last column wise
print(b[-1,-1]) #last
print(b[-2,-1]) #second last column wise
print(b[-1,-2]) #second last row wise

1
2
4
9
5
6


In [72]:
#for c (1 dim)
print(c[0]) #first
print(c[1]) #second
print(c[-1]) #last
print(c[-2]) #second last

1
3
19
17


In [73]:
#for d (2 dim)
print(d[0,0]) #first
print(d[0,1]) #second last row wise
print(d[1,0]) #second last column wise
print(d[-1,-1]) #last
print(d[-2,-1]) #second last column wise
print(d[-1,-2]) #second last row wise

0.0
0.0
0.0
0.0
0.0
0.0


In [74]:
#for e (2 dim)
print(e[0,0]) #first
print(e[0,1]) #second last row wise
print(e[1,0]) #second last column wise
print(e[1,-1]) #last
print(e[-2,-1]) #second last column wise
print(e[-1,-2]) #second last row wise

2.4
2.4
2.4
2.4
2.4
2.4


In [128]:
#for f (2 dim)
print(f[0,0]) #first
print(f[0,1]) #second last row wise
print(f[1,0]) #second last column wise
print(f[1,-1]) #last
print(f[-2,-1]) #second last column wise
print(f[-1,-2]) #second last row wise

2
5
17
29
14
26


In [81]:
#for g (2 dim)
print(g[0,0]) #first
print(g[0,1]) #second last row wise
print(g[1,0]) #second last column wise
print(g[-1,-1]) #last
print(g[-2,-1]) #second last column wise
print(g[-1,-2]) #second last row wise

-1
-2
-7
-1
-6
-15


In [82]:
#for h (2 dim)
print(h[0,0]) #first
print(h[0,1]) #second last row wise
print(h[1,0]) #second last column wise
print(h[-1,-1]) #last
print(h[-2,-1]) #second last column wise
print(h[-1,-2]) #second last row wise

0.45305902675862453
0.019806248145854966
0.39822657538031625
0.5943132331668244
0.654483405167205
0.6698951562102261


##### c) In all 1-dimensional array create in Q.1, display first 3 three elements, and last three elements.

In [91]:
# for a 
print(a[0:3]) # first 3 elements
print(a[-3:]) # last 3 elements

[-1 -2 -3]
[-12 -15  -1]


In [92]:
# for c 
print(c[0:3]) # first 3 elements
print(c[-3:]) # last 3 elements

[1 3 5]
[15 17 19]


##### d) In all 2-dimensional array created in Q.1, display all the elements in first row, second column in array.

In [93]:
#for b
print(b[0:1,0:])
print(b[0:,1:2])

[[1 2 1 4 5 5]]
[[2]
 [5]]


In [94]:
#for d
print(d[0:1,0:])
print(d[0:,1:2])

[[0. 0. 0. 0. 0.]]
[[0.]
 [0.]
 [0.]
 [0.]]


In [95]:
#for e
print(e[0:1,0:])
print(e[0:,1:2])

[[2.4 2.4 2.4 2.4]]
[[2.4]
 [2.4]
 [2.4]]


In [129]:
#for f
print(f[0:1,0:])
print(f[0:,1:2])

[[ 2  5  8 11 14]]
[[ 5]
 [20]]


In [98]:
#for g
print(g[0:1,0:])
print(g[0:,1:2])

[[-1 -2 -3 -3 -6]]
[[ -2]
 [-17]]


In [99]:
#for h
print(h[0:1,0:])
print(h[0:,1:2])

[[0.45305903 0.01980625 0.33845973 0.06215952 0.67024461]]
[[0.01980625]
 [0.97086345]
 [0.84840827]
 [0.43703767]]


# Q3

#####  a) Add, subtract, multiply and divide the array created in Q1. a and Q1. C. Perform the same operation on the array created in Q1. D and Q1. h.

In [106]:
# for  a and Q1. C 
print(a+c) # addition
print(a-c) #subtraction
print(a*c) #multiplication
print(a/c) #division

[ 0  1  2  4  3  4 -4  3  2 18]
[ -2  -5  -8 -10 -15 -18 -30 -27 -32 -20]
[  -1   -6  -15  -21  -54  -77 -221 -180 -255  -19]
[-1.         -0.66666667 -0.6        -0.42857143 -0.66666667 -0.63636364
 -1.30769231 -0.8        -0.88235294 -0.05263158]


In [107]:
# for D and Q1. h.
print(d+h) # addition
print(d-h) #subtraction
print(d*h) #multiplication
print(d/h) #division

[[0.45305903 0.01980625 0.33845973 0.06215952 0.67024461]
 [0.39822658 0.97086345 0.58622444 0.82871962 0.36224319]
 [0.27812149 0.84840827 0.56680048 0.22792051 0.65448341]
 [0.02468703 0.43703767 0.83429562 0.66989516 0.59431323]]
[[-0.45305903 -0.01980625 -0.33845973 -0.06215952 -0.67024461]
 [-0.39822658 -0.97086345 -0.58622444 -0.82871962 -0.36224319]
 [-0.27812149 -0.84840827 -0.56680048 -0.22792051 -0.65448341]
 [-0.02468703 -0.43703767 -0.83429562 -0.66989516 -0.59431323]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


##### b) Find the square root of the all element of array created in Q1 c

In [112]:
print(np.sqrt(c))

[1.         1.73205081 2.23606798 2.64575131 3.         3.31662479
 3.60555128 3.87298335 4.12310563 4.35889894]


##### c) Display square of all elements created in the array Q1. f.

In [114]:
print(np.square(f1))

[[[  4  25  64 121 196]]

 [[289 400 529 676 841]]]


##### d) Display the sign of each element created in the array Q1. h.

In [115]:
print(np.sign(h))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Q.4

##### a) Find the transpose of all 2-dimensional array created in Q1.


In [118]:
print(b.transpose()) # for b

[[1 4]
 [2 5]
 [1 8]
 [4 4]
 [5 6]
 [5 9]]


In [18]:
np.transpose(b)

array([[1, 4],
       [2, 5],
       [1, 8],
       [4, 4],
       [5, 6],
       [5, 9]])

In [119]:
print(d.transpose()) # for d

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [120]:
print(e.transpose()) # for e

[[2.4 2.4 2.4]
 [2.4 2.4 2.4]
 [2.4 2.4 2.4]
 [2.4 2.4 2.4]]


In [130]:
print(f.transpose()) # for f

[[ 2 17]
 [ 5 20]
 [ 8 23]
 [11 26]
 [14 29]]


In [121]:
print(g.transpose()) # for g

[[ -1  -7]
 [ -2 -17]
 [ -3 -12]
 [ -3 -15]
 [ -6  -1]]


In [122]:
print(h.transpose()) # for h

[[0.45305903 0.39822658 0.27812149 0.02468703]
 [0.01980625 0.97086345 0.84840827 0.43703767]
 [0.33845973 0.58622444 0.56680048 0.83429562]
 [0.06215952 0.82871962 0.22792051 0.66989516]
 [0.67024461 0.36224319 0.65448341 0.59431323]]


##### b) Sort all the 1-dimensional array created in Q1 in ascending order

In [32]:
#for a
srt_a=np.sort(a)
print(srt_a)


[-17 -15 -12  -7  -6  -3  -3  -2  -1  -1]


In [31]:
#for a# for decending
srt_a=-np.sort(-a)
print(srt_a)

[ -1  -1  -2  -3  -3  -6  -7 -12 -15 -17]


In [21]:
#for c
srt_c=np.sort(c)
print(srt_c)

[ 1  3  5  7  9 11 13 15 17 19]


In [22]:
print(c.sort())

None


##### c) Sort all the 1-dimensional array created in Q1 in descending order

In [138]:
#for a
a[::-1].sort()
print(a)

[ -1  -1  -2  -3  -3  -6  -7 -12 -15 -17]


In [139]:
#for c
c[::-1].sort()
print(c)

[19 17 15 13 11  9  7  5  3  1]


##### d) Sort all 2-dimensional array created in Q1 in ascending order row wise.

In [30]:
#for b
srt_b=np.sort(b,axis=1)
print(srt_b)

[[1 1 2 4 5 5]
 [4 4 5 6 8 9]]


In [142]:
#for d
srt_d=np.sort(d,axis=1)
print(srt_d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [143]:
#for e
srt_e=np.sort(e,axis=1)
print(srt_e)

[[2.4 2.4 2.4 2.4]
 [2.4 2.4 2.4 2.4]
 [2.4 2.4 2.4 2.4]]


In [144]:
#for f
srt_f=np.sort(f,axis=1)
print(srt_f)

[[ 2  5  8 11 14]
 [17 20 23 26 29]]


In [145]:
#for g
srt_g=np.sort(g,axis=1)
print(srt_g)

[[ -3  -3  -2  -1  -1]
 [-17 -15 -12  -7  -6]]


In [146]:
#for h
srt_h=np.sort(h,axis=1)
print(srt_h)

[[0.01980625 0.06215952 0.33845973 0.45305903 0.67024461]
 [0.36224319 0.39822658 0.58622444 0.82871962 0.97086345]
 [0.22792051 0.27812149 0.56680048 0.65448341 0.84840827]
 [0.02468703 0.43703767 0.59431323 0.66989516 0.83429562]]


##### e) Sort all 2-dimensional array create in Q1 in descending order column wise.

In [151]:
#for b
dsrt_b=-np.sort(-b, axis=0)
print(dsrt_b)

[[4 5 8 4 6 9]
 [1 2 1 4 5 5]]


In [152]:
#for d
dsrt_d=-np.sort(-d, axis=0)
print(dsrt_d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [153]:
#for e
dsrt_e=-np.sort(-e, axis=0)
print(dsrt_e)

[[2.4 2.4 2.4 2.4]
 [2.4 2.4 2.4 2.4]
 [2.4 2.4 2.4 2.4]]


In [154]:
#for f
dsrt_f=-np.sort(-f, axis=0)
print(dsrt_f)

[[17 20 23 26 29]
 [ 2  5  8 11 14]]


In [155]:
#for g
dsrt_g=-np.sort(-g, axis=0)
print(dsrt_g)

[[ -1  -1  -2  -3  -3]
 [ -6  -7 -12 -15 -17]]


In [156]:
#for h
dsrt_h=-np.sort(-h, axis=0)
print(dsrt_h)

[[0.45305903 0.97086345 0.83429562 0.82871962 0.67024461]
 [0.39822658 0.84840827 0.58622444 0.66989516 0.65448341]
 [0.27812149 0.43703767 0.56680048 0.22792051 0.59431323]
 [0.02468703 0.01980625 0.33845973 0.06215952 0.36224319]]


##### f) Create new 1-dimensional array by joining all 1-dinensional array created in Q1.

In [164]:
con1=np.concatenate([a,c])
print(con1)

[ -1  -1  -2  -3  -3  -6  -7 -12 -15 -17  19  17  15  13  11   9   7   5
   3   1]


##### g) Create a new 2-dimensional array by joining 2-dimensioanl array Q1 d, Q1 h along x-axis.


In [166]:
con2_x=np.concatenate([d,h],axis=1)
print(con2)

[[0.         0.         0.         0.         0.         0.45305903
  0.01980625 0.33845973 0.06215952 0.67024461]
 [0.         0.         0.         0.         0.         0.39822658
  0.97086345 0.58622444 0.82871962 0.36224319]
 [0.         0.         0.         0.         0.         0.27812149
  0.84840827 0.56680048 0.22792051 0.65448341]
 [0.         0.         0.         0.         0.         0.02468703
  0.43703767 0.83429562 0.66989516 0.59431323]]


##### h) Create a new 2-dimensional array by joining 2-dimensioanl array Q1 d, Q1 h along y-axis.

In [167]:
con2_y=np.concatenate([d,h],axis=0)
print(con2_y)

[[0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.45305903 0.01980625 0.33845973 0.06215952 0.67024461]
 [0.39822658 0.97086345 0.58622444 0.82871962 0.36224319]
 [0.27812149 0.84840827 0.56680048 0.22792051 0.65448341]
 [0.02468703 0.43703767 0.83429562 0.66989516 0.59431323]]


# Q5

##### a) Find the maximum, minimum, mean and standard deviation of all 1-dimensional  array created in Q1.


In [172]:
# for a
print(np.max(a)) #maximum 
print(np.min(a)) #minimum
print(np.mean(a)) #mean 
print(np.std(a)) #standard deviation

-1
-17
-6.7
5.64003546088143


In [173]:
# for c
print(np.max(c)) #maximum 
print(np.min(c)) #minimum
print(np.mean(c)) #mean
print(np.std(c)) #standard deviation

19
1
10.0
5.744562646538029


##### b) Find the maximum, minimum, mean and standard deviation of all 2- dimensional array created in Q1 along the x-axis.


In [184]:
#for b
print(np.max(b,axis=1)) #maximum
print(np.min(b,axis=1)) #minimum
print(np.mean(b,axis=1)) #mean
print(np.std(b,axis=1)) #standerd deviation

[5 9]
[1 4]
[3. 6.]
[1.73205081 1.91485422]


In [182]:
#for d
print(np.max(d,axis=1)) #maximum
print(np.min(d,axis=1)) #minimum
print(np.mean(d,axis=1)) #mean
print(np.std(d,axis=1)) #standerd deviation

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]


In [185]:
#for e
print(np.max(e,axis=1)) #maximum
print(np.min(e,axis=1)) #minimum
print(np.mean(e,axis=1)) #mean
print(np.std(e,axis=1)) #standerd deviation

[2.4 2.4 2.4]
[2.4 2.4 2.4]
[2.4 2.4 2.4]
[0. 0. 0.]


In [186]:
#for f
print(np.max(f,axis=1)) #maximum
print(np.min(f,axis=1)) #minimum
print(np.mean(f,axis=1)) #mean
print(np.std(f,axis=1)) #standerd deviation

[14 29]
[ 2 17]
[ 8. 23.]
[4.24264069 4.24264069]


In [187]:
#for g
print(np.max(g,axis=1)) #maximum
print(np.min(g,axis=1)) #minimum
print(np.mean(g,axis=1)) #mean
print(np.std(g,axis=1)) #standerd deviation

[-1 -6]
[ -3 -17]
[ -2.  -11.4]
[0.89442719 4.31740663]


In [188]:
#for h
print(np.max(h,axis=1)) #maximum
print(np.min(h,axis=1)) #minimum
print(np.mean(h,axis=1)) #mean
print(np.std(h,axis=1)) #standerd deviation

[0.67024461 0.97086345 0.84840827 0.83429562]
[0.01980625 0.36224319 0.22792051 0.02468703]
[0.30874583 0.62925546 0.51514683 0.51204574]
[0.24359042 0.23790903 0.23316343 0.27519959]


##### c) Find the maximum, minimum, mean and standard deviation of all 2-dimensional array created in Q1 along the y-axis.

In [189]:
#for b
print(np.max(b,axis=0)) #maximum
print(np.min(b,axis=0)) #minimum
print(np.mean(b,axis=0)) #mean
print(np.std(b,axis=0)) #standerd deviation

[4 5 8 4 6 9]
[1 2 1 4 5 5]
[2.5 3.5 4.5 4.  5.5 7. ]
[1.5 1.5 3.5 0.  0.5 2. ]


In [190]:
#for d
print(np.max(d,axis=0)) #maximum
print(np.min(d,axis=0)) #minimum
print(np.mean(d,axis=0)) #mean
print(np.std(d,axis=0)) #standerd deviation

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]


In [191]:
#for e
print(np.max(e,axis=0)) #maximum
print(np.min(e,axis=0)) #minimum
print(np.mean(e,axis=0)) #mean
print(np.std(e,axis=0)) #standerd deviation

[2.4 2.4 2.4 2.4]
[2.4 2.4 2.4 2.4]
[2.4 2.4 2.4 2.4]
[0. 0. 0. 0.]


In [192]:
#for f
print(np.max(f,axis=0)) #maximum
print(np.min(f,axis=0)) #minimum
print(np.mean(f,axis=0)) #mean
print(np.std(f,axis=0)) #standerd deviation

[17 20 23 26 29]
[ 2  5  8 11 14]
[ 9.5 12.5 15.5 18.5 21.5]
[7.5 7.5 7.5 7.5 7.5]


In [193]:
#for g
print(np.max(g,axis=0)) #maximum
print(np.min(g,axis=0)) #minimum
print(np.mean(g,axis=0)) #mean
print(np.std(g,axis=0)) #standerd deviation

[-1 -1 -2 -3 -3]
[ -6  -7 -12 -15 -17]
[ -3.5  -4.   -7.   -9.  -10. ]
[2.5 3.  5.  6.  7. ]


In [194]:
#for h
print(np.max(h,axis=0)) #maximum
print(np.min(h,axis=0)) #minimum
print(np.mean(h,axis=0)) #mean
print(np.std(h,axis=0)) #standerd deviation

[0.45305903 0.97086345 0.83429562 0.82871962 0.67024461]
[0.02468703 0.01980625 0.33845973 0.06215952 0.36224319]
[0.28852353 0.56902891 0.58144507 0.4471737  0.57032111]
[0.16494286 0.37369474 0.17550825 0.31284581 0.12343018]
