In [1]:
import numpy as np

In [5]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
a[0,0]=12

In [7]:
a

array([[12.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [13]:
a2=np.random.randn(7,2)

In [14]:
a2

array([[ 1.93713827, -0.78925301],
       [ 1.14696318, -0.92338353],
       [ 0.57552901,  0.9689369 ],
       [-0.35491365, -0.18086602],
       [ 0.54188675, -1.02256158],
       [-0.76867295, -0.9778195 ],
       [-0.31815701,  0.53845382]])

In [16]:
e=np.arange(10)

In [18]:
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.sqrt(e)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [20]:
np.exp(e)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [21]:
p=np.random.randn(3,3)

In [22]:
p

array([[ 1.29953045,  0.61043406, -0.86048902],
       [-0.35091793,  0.42657661,  1.67173141],
       [ 0.17756651,  0.1039848 , -0.6070586 ]])

In [25]:
np.sort(p,axis=None)

array([-0.86048902, -0.6070586 , -0.35091793,  0.1039848 ,  0.17756651,
        0.42657661,  0.61043406,  1.29953045,  1.67173141])